version: '3.8'

services:

  db:
    image: mysql:8
    container_name: techguess-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techguess
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  api:
    image: node:18
    container_name: techguess-api
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: techguess
    command: sh -c "npm install && node server.js"

  web:
    image: nginx:alpine
    container_name: techguess-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api

volumes:
  mysql_data: