name: TechGuess CI Pipeline

on:
  push:
    branches: [ main, melhorias, testes ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Instalar dependências
        run: npm install

      # 🔹 Testes unitários (Jest)
      - name: Rodar testes unitários (Jest)
        run: npm test

      # 🔹 Subir servidor para Cypress
      - name: Instalar servidor HTTP
        run: npm install -g http-server

      - name: Iniciar servidor
        run: |
          http-server . -p 5500 --silent &
          sleep 5

      # 🔹 Testes E2E (Cypress)
      - name: Rodar testes E2E (Cypress)
        run: npm run test:cypress

      - name: Finalizar servidor
        run: kill $(lsof -t -i:5500) || true

      - name: Pipeline concluída
        run: echo "Build executado com sucesso 🚀"